### PR TITLE
Proper tests

### PR DESCRIPTION
**Pull request by rustkas**
1. Add proper tests for depcache module.
2. Add launching proper test by Makefile.
3. Move dializer launching to rebar3 test profile.
4. Add changes to rebar.config.

### CODE REVIEW

**Comment by mworrell** [comment]
It seems that proper doesn't support OTP 19, I am ok with removing that test target.

**Comment by rustkas** [comment]
> It seems that proper doesn't support OTP 19, I am ok with removing that test target.

Ok.

**Comment by mworrell** [comment]
Maybe just remove the whole OTP 19.3 tests from the .GH tests?

https://github.com/zotonic/depcache/blob/888445a7d3f96ed6dfd54f522dab205dbd17f113/.github/workflows/test.yml#L21

And then, maybe, add OTP 24?

**Comment by mworrell** [comment]
Just checked manually, and indeed 20.3 and 23 both pass the tests.

**Comment by rustkas** [comment]
> Maybe just remove the whole OTP 19.3 tests from the .GH tests?
> 
> https://github.com/zotonic/depcache/blob/888445a7d3f96ed6dfd54f522dab205dbd17f113/.github/workflows/test.yml#L21
> 
> And then, maybe, add OTP 24?

Yes. Of couse.

**Comment by mworrell** [comment]
Everything passes 🥳  Merging!

And thank you again!

**Comment by mworrell** [comment]
Released version 1.9.0

**Pull request merged**
