### PR TITLE
Improving documentation

### PR DESCRIPTION
**Pull request by rustkas**
I've made a brachname more informative.

Description of changes:
- Provide more information about function definitons of depcache API.
- Implement EDoc options (provide CSS file with styles, add overview file). Add new folder `doc_src` which contains additional files for documentation generation.
- Implement overload option of EDoc function description.
- Show hidden documetation. Add EDoc tags for it. Provide rebar3 option - add additional profile for EDoc private documentation.
- Separate some functions to make the code easier to read.
- Makefile: add additional actions for `edoc`, `clean` comands; add new command `edoc_private`.

### CODE REVIEW

**Comment by rustkas** [comment]
I renamed my previous branch to bring it in line with previous commit branches of this library.

**Comment by rustkas** [comment]
I decided to duplicate this branch (please ignore this branch) to make the commit name more informative (`fix_doc`). After making changes using `rustkas:fix_doc`, I will delete this branch.

**Comment by mworrell** [comment]
I am a bit confused, do you want me to merge this?

**Comment by rustkas** [comment]
Yes. I got a little confused while making the named branch. I wanted to make pull request in elegant way. That is way I had to close the previous pull request.

**Comment by mworrell** [comment]
Thanks!

**Pull request merged**
